language: node_js
sudo: false
node_js: lts/*

install: yarn install --check-files

before_install:
  - npm install -g greenkeeper-lockfile yarn
  - greenkeeper-lockfile-update

before_script: if [[ $GH_TOKEN ]]; then ./prepare-gpg-key.sh; fi;

cache:
  yarn: true
  directories:
    - node_modules

before_cache: rm -rf node_modules/.cache

script: if [[ $GH_TOKEN ]]; then semantic-release --dry-run; fi;

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release
  on:
    branch: master
